@server=http://localhost:4004


### MonitoredArtifacts
# @name MonitoredArtifacts_GET
GET {{server}}/Admin/MonitoredArtifacts



### MonitoredArtifacts
# @name MonitoredArtifacts_POST
POST {{server}}/Admin/MonitoredArtifacts
Content-Type: application/json

{
  "ID": "23193772-4714-421c-a37d-9f32720cc77f",
  "iFlowName": "iFlowName-23193772",
  "iFlowId": "iFlowId-23193772",
  "namespace": "namespace-23193772",
  "isActive": true,
  "lastPollTimestamp": "2014-07-16T00:00:00.000Z",
  "createdAt": "2020-10-14T00:00:00.000Z",
  "createdBy": "createdBy.dt4fg@example.org",
  "modifiedAt": "2004-12-27T00:00:00.000Z",
  "modifiedBy": "modifiedBy.dt4fg@example.net"
}


### MonitoredArtifacts
# @name MonitoredArtifacts_PATCH
PATCH {{server}}/Admin/MonitoredArtifacts/23193772-4714-421c-a37d-9f32720cc77f
Content-Type: application/json

{
  "ID": "23193772-4714-421c-a37d-9f32720cc77f",
  "iFlowName": "iFlowName-23193772",
  "iFlowId": "iFlowId-23193772",
  "namespace": "namespace-23193772",
  "isActive": true,
  "lastPollTimestamp": "2014-07-16T00:00:00.000Z",
  "createdAt": "2020-10-14T00:00:00.000Z",
  "createdBy": "createdBy.dt4fg@example.org",
  "modifiedAt": "2004-12-27T00:00:00.000Z",
  "modifiedBy": "modifiedBy.dt4fg@example.net"
}


### MonitoredArtifacts
# @name MonitoredArtifacts_DELETE
DELETE {{server}}/Admin/MonitoredArtifacts/23193772-4714-421c-a37d-9f32720cc77f
Content-Type: application/json


### TokenUsages
# @name TokenUsages_GET
GET {{server}}/Admin/TokenUsages



### TokenUsages
# @name TokenUsages_POST
POST {{server}}/Admin/TokenUsages
Content-Type: application/json

{
  "ID": "2469199c-5ed3-4fe8-b634-ea4ea6dc5d2c",
  "model": "model-2469199",
  "inputTokens": 17,
  "outputTokens": 6,
  "estimatedCostUSD": 431720.3225,
  "calledAt": "2001-01-13T00:00:00.000Z",
  "purpose": "purpose-2469199",
  "createdAt": "2001-06-27T00:00:00.000Z",
  "createdBy": "createdBy.1gx8v@example.com",
  "modifiedAt": "2010-09-26T00:00:00.000Z",
  "modifiedBy": "modifiedBy.1gx8v@example.org"
}


### TokenUsages
# @name TokenUsages_PATCH
PATCH {{server}}/Admin/TokenUsages/2469199c-5ed3-4fe8-b634-ea4ea6dc5d2c
Content-Type: application/json

{
  "ID": "2469199c-5ed3-4fe8-b634-ea4ea6dc5d2c",
  "model": "model-2469199",
  "inputTokens": 17,
  "outputTokens": 6,
  "estimatedCostUSD": 431720.3225,
  "calledAt": "2001-01-13T00:00:00.000Z",
  "purpose": "purpose-2469199",
  "createdAt": "2001-06-27T00:00:00.000Z",
  "createdBy": "createdBy.1gx8v@example.com",
  "modifiedAt": "2010-09-26T00:00:00.000Z",
  "modifiedBy": "modifiedBy.1gx8v@example.org"
}


### TokenUsages
# @name TokenUsages_DELETE
DELETE {{server}}/Admin/TokenUsages/2469199c-5ed3-4fe8-b634-ea4ea6dc5d2c
Content-Type: application/json
