/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("IncidentClustersListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheIncidentClustersList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheIncidentClustersList.onFilterBar().iCheckFilterField("Severity");
            Then.onTheIncidentClustersList.onFilterBar().iCheckFilterField("Status");
            Then.onTheIncidentClustersList.onFilterBar().iCheckFilterField("iFlowName");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheIncidentClustersList.onTable().iCheckColumns(6, {"iFlowName":{"header":"iFlow Name"},"errorSignature":{"header":"Error Type"},"incidentCount":{"header":"Incident Count"},"severity":{"header":"Severity"},"status":{"header":"Status"},"lastSeen":{"header":"Last Seen"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheIncidentClustersList.onFilterBar().iExecuteSearch();
            
            Then.onTheIncidentClustersList.onTable().iCheckRows();

            When.onTheIncidentClustersList.onTable().iPressRow(0);
            Then.onTheIncidentClustersObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});